// @generated — do not edit. Regenerated by rsbuild on every build.
// Source of truth: web/ directory.

export interface PrecacheEntry {
	url: string;
	revision: string;
}

export const PRECACHE_MANIFEST: PrecacheEntry[] = [
	{
		"url": "favicon.png",
		"revision": "362fabc3efb9678c46c1c5efc4c67fb3dcdcdfc000c8e7f0171aa0bd05e97fdd"
	},
	{
		"url": "icons/Icon-192.png",
		"revision": "39c8684354d965bbb6344b1367f114cc7ef8db81bb43c2560bd950f93f4c4507"
	},
	{
		"url": "icons/Icon-512.png",
		"revision": "f8d659c4ad2354019e2b64d1cf14c6744930fee84f20bb5969af45bcd989d6e8"
	},
	{
		"url": "icons/Icon-maskable-192.png",
		"revision": "39c8684354d965bbb6344b1367f114cc7ef8db81bb43c2560bd950f93f4c4507"
	},
	{
		"url": "icons/Icon-maskable-512.png",
		"revision": "f8d659c4ad2354019e2b64d1cf14c6744930fee84f20bb5969af45bcd989d6e8"
	},
	{
		"url": "index.html",
		"revision": "4efcde2e3e2a1f23554f68eae03ec796be9ca3604498800cf44a3434a12b54c7"
	},
	{
		"url": "manifest.json",
		"revision": "1b3d571a8a4ecdf80517aac091a317d5b83af9b9f4633c829c08ae91060c1ea0"
	}
];
