import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig, type RsbuildPlugin } from "@rsbuild/core";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const webDir = resolve(repoRoot, "web");
const manifestPath = resolve(__dirname, "src/precache-manifest.generated.ts");

// precache 排除：
// - sw.js：service worker 自己，不能 precache 自己
// - flutter_bootstrap.js：Flutter build 時會替換內容（serviceWorkerVersion
//   等模板變數），precache 它會卡舊版
// - og-preview.jpg：social share 預覽圖、瀏覽器不需要
const EXCLUDE = new Set<string>([
	"sw.js",
	"sw.js.map",
	"flutter_bootstrap.js",
	"og-preview.jpg",
]);

interface PrecacheEntry {
	url: string;
	revision: string;
}

function walk(dir: string, base: string, out: string[]): void {
	for (const name of readdirSync(dir)) {
		const full = join(dir, name);
		const rel = relative(base, full).replaceAll("\\", "/");
		if (statSync(full).isDirectory()) {
			walk(full, base, out);
		} else if (!EXCLUDE.has(rel)) {
			out.push(rel);
		}
	}
}

function sha256(file: string): string {
	return createHash("sha256").update(readFileSync(file)).digest("hex");
}

function buildManifest(): PrecacheEntry[] {
	const files: string[] = [];
	walk(webDir, webDir, files);
	files.sort();
	return files.map((rel): PrecacheEntry => ({
		url: rel,
		revision: sha256(join(webDir, rel)),
	}));
}

function writeManifest(entries: PrecacheEntry[]): void {
	// 寫成 TS module、SW 可直接 import；附 generation timestamp 註解但不寫到
	// 程式碼裡（不影響 hash 比對、避免每次 build diff 都動）。
	const body = `// @generated — do not edit. Regenerated by rsbuild on every build.
// Source of truth: web/ directory.

export interface PrecacheEntry {
	url: string;
	revision: string;
}

export const PRECACHE_MANIFEST: PrecacheEntry[] = ${JSON.stringify(entries, null, "\t")};
`;
	writeFileSync(manifestPath, body, "utf8");
}

const precacheManifestPlugin: RsbuildPlugin = {
	name: "precache-manifest",
	setup(api): void {
		// build 開始前先生 manifest；watch 模式下每次 rebuild 也會跑
		api.onBeforeBuild(() => {
			const entries = buildManifest();
			writeManifest(entries);
			console.info(`[precache] generated ${entries.length} entries`);
		});
	},
};

export default defineConfig({
	plugins: [precacheManifestPlugin],
	source: {
		entry: {
			sw: resolve(__dirname, "src/sw.ts"),
		},
		tsconfigPath: resolve(__dirname, "tsconfig.json"),
	},
	output: {
		target: "web-worker",
		distPath: {
			root: webDir,
			js: "", // 直接放在 web/ 根目錄（SW 必須與要控制的 scope 同層）
			jsAsync: "",
		},
		filename: {
			js: "[name].js",
		},
		cleanDistPath: false,
		// SW 不能 emit 額外的 asset / split chunk，全部 inline
		sourceMap: false,
		minify: true,
	},
	performance: {
		chunkSplit: {
			strategy: "all-in-one",
		},
	},
});
