// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLFX6u5GAO_auxPHFMjT7nEArF1XBi6T4',
    appId: '1:369520887416:web:66683876aad03c94160f8d',
    messagingSenderId: '369520887416',
    projectId: 'kid-puzzle-f0f39',
    authDomain: 'kid-puzzle-f0f39.firebaseapp.com',
    storageBucket: 'kid-puzzle-f0f39.firebasestorage.app',
    measurementId: 'G-VWMRLEQHPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARvUKIpgovT0ZPj_5T557x_QjY53IlR7A',
    appId: '1:369520887416:android:b9ebf99d3c9858d1160f8d',
    messagingSenderId: '369520887416',
    projectId: 'kid-puzzle-f0f39',
    storageBucket: 'kid-puzzle-f0f39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmwUclVuzxqlZYVgdnwkf4qmhR5FVoYrU',
    appId: '1:369520887416:ios:221f9b9b9018d1b9160f8d',
    messagingSenderId: '369520887416',
    projectId: 'kid-puzzle-f0f39',
    storageBucket: 'kid-puzzle-f0f39.firebasestorage.app',
    iosBundleId: 'com.abstreamace.kidPuzzle',
  );
}
